# Site settings
title: Justin Harder's ML Blog
email: your-email@example.com
description: >-
  Justin Harder's blog on machine learning, computer vision, and large language models.
baseurl: "/About-Me" # the subpath of your site, e.g. /blog
url: "https://justintienken-harder.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: your_twitter
github_username:  your_github

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - .idea/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"